### ISSUE TITLE
Doesn't load pictures after updating extension 1.3.1 to 1.6.0

### ISSUE THREAD

**Issue by hd321kbps** [AlfredoRamos/phpbb-ext-imgur#77]
Doesn't load pictures after updating extension 1.3.1 to 1.6.0

Error 500.
phpBB 3.3.1
Php 7.3.20
In logs:

```
[31-Aug-2020 16:13:11 Europe/Moscow] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\_idn_uri_convert() in /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/guzzlehttp/guzzle/src/Client.php:220
Stack trace:
#0 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/guzzlehttp/guzzle/src/Client.php(155): GuzzleHttp\Client->buildUri(Object(GuzzleHttp\Psr7\Uri), Array)
#1 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/guzzlehttp/guzzle/src/Client.php(183): GuzzleHttp\Client->requestAsync('POST', 'image', Array)
#2 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/HttpClient/HttpClient.php(115): GuzzleHttp\Client->request('POST', 'image', Array)
#3 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/HttpClient/HttpClient.php(85): Imgur\HttpClient\HttpClient->performRequest('image', Array, 'POST')
#4 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/Api/AbstractApi.php(64): Imgur\HttpClient\HttpClient->post('image', Array)
#5 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/j0k3r/php-imgur-api-client/lib/Imgur/Api/Image.php(55): Imgur\Api\AbstractApi->post('image', Array)
#6 /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/controller/imgur.php(282): Imgur\Api\Image->upload(Array)
#7 /home/n/nosipova/magicclover.ru/public_html/vendor/symfony/http-kernel/HttpKernel.php(151): alfredoramos\imgur\controller\imgur->upload('17477383')
#8 /home/n/nosipova/magicclover.ru/public_html/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(phpbb\symfony_request), 1)
#9 /home/n/nosipova/magicclover.ru/public_html/app.php(35): Symfony\Component\HttpKernel\HttpKernel->handle(Object(phpbb\symfony_request))
#10 {main}
  thrown in /home/n/nosipova/magicclover.ru/public_html/ext/alfredoramos/imgur/vendor/guzzlehttp/guzzle/src/Client.php on line 220
```

**Comment by AlfredoRamos** [comment]
Hi,

- How did you update the extension?
- Where did you download the 1.6.0 version?
- Did you deleted **all** the files and directories before uploading the new ones?

That function call does not exist in that file, it has been replaced to `Utils::idnUriConvert()` for some time now, so make sure to remove all the files from the extension before uploading the new ones.

And do not download the extension from GitHub, since it doesn't have the dependencies it needs.

It can only be downloaded from phpbb.com for a complete extension package:

https://www.phpbb.com/customise/db/extension/imgur/support/topic/198266

**Comment by hd321kbps** [comment]
An update to remove all directories resolved the issue.
Thank you.
